##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: MUZIKS
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Learn Music about Eraserheads
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This is About enjoying Musics and want to be a Musician. Musics makes me feel better and comfortable. A music enthusiast tends to have a heightened sensitivity to sounds, rhythms, and melodies. They often actively listen to a wide variety of music, analyzing lyrics, instrumentation, and production quality. This appreciation extends beyond casual enjoyment; they may attend live concerts, follow favorite artists closely, and stay informed about new releases and musical trends. Their personal spaces—rooms, cars, and devices—are often filled with music, playlists, or musical memorabilia.
Behaviorally, music enthusiasts may engage in multiple music-related activities. Many play instruments, sing, or produce music, while others dedicate time to curating playlists, debating music theory, or collecting vinyl records and CDs."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Rico Montesa, Jeric Tura, Aaron Rodriquez, Joshua Piojo

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
